### ISSUE TITLE
Great, but...

### ISSUE THREAD

**Issue by BarbaricDuck** [elmoiv/battletexthack#1]
A few things I've noticed, the bot will input a word mor than one, also, some words are too long, but apart from that great bot, I love how it works

**Comment by elmoiv** [comment]
Hi @bengroves2004 

I added new functions to my script that you may find helpful for this issue:
  - I added a `word_history` to _prevent duplicates_.
  - I updated the code with a new function called `smart_randomizer()`:
    * This function can simulate a human typing.
    * You can select between **Robot** or **Human** when you start the script.

Have fun :)
